language: node_js
deploy:
  provider: heroku
  api_key:
    secure: cXhDtNX9U1sHP6ket6YRMAB0EDos9toUEey4PAeVNEl8pW2CaY36llX8Awy33pi+NAmJ4TBKWqvKw4IBjlocItIJzLmeJ5Xo88xA1WCDawl+rcpDOYXtnXri7pO+Qg9UgjlZfZklLK6ZCuSCIngeRzjGi8ZWa1+6N2ODsm9Qy6wz6631cJJ/3gVjiBpjKbuXG8GUHTVt9f24goDUfOUXMlgUBWUp1T3LdG4IxjJ0W7rkEzJb5gUciiLbO9Trla/EEaUKfaW8UctDanFwqQeMORDUuZsEKR8OBTDwGRPhEbAfW/poRhC3xcZxGDba40YKfIOfJLmEanPFdVR1YH6oq3dKBb2zDdkrRlk2TJhj0YCCno5mR/Ci8VVvc/69oewbeI1VPMG+J/ieTJU4flRuq7tv14ODBB1uTu2ABcaFoY7BB88DVHyZM4jXysN6p3B4+HmmbiCI7nATmpC+pmqrWZ4lPBLpbf568IMD46g93+ncpAmyEsNbqZtBM5efqf+5xGlcgzwDEVZV1jGvBijRPAPWFE0Mr1M1wzqmZTszjhSSsSkvtuaaFd6OZtRHj+3tuPIrhvml3qvO3CmFpBOxxeQbFNeX+MNBhEmSdbI370QgsZVwm1QwVg2gL8rqvqwokQoSyENqTumMMaXkVhqxs9/A7KUL3LgdPYPpZmPNWjg=
  app: hearafrica-api
