language: node_js
deploy:
  provider: heroku
  api_key:
    secure: eZIs4qtw1ErST2Jx+UD0hTI0Up7XkTdpYMUJuQNXJwwy8F9aqE/o9p8fuVkf+l3ed6dWvdYt3jCe9bitZ1UZFM88+AL+rHmvzhbykvObtgphNc/9IlrBtpJtdStNwXiz5Fm3qno91N7Ut1TMPAiWsnVMPkPUL+C/pvkY4nnZnUCrto2maRNWb4bWNQKMSnwxUShLBBUrMsRVUWJhCsEQg/xjDPemTIcUu+GZP9IwoNt0lMbF0YAOx6PYhF4CPX2ySy5Heq2AbfYUNEpsN3ow9dOFTcMOPr0p9oqPg4JCUglDVVc+ZbHdK8ZUawZ3gwl+jvVhrF6S98nMMTULzVHT1hS8ik36oQddRaEi4bCqUAH6RKp7fMdKH+NOCN0ULJ/1M6nBE5NnK6qEsimc+UIXrSYiEoAHrXfTl1HpJvRMnokwEkOw3yFCyauIZwDWy14nFs2PylGc3w8PVYNtKxTSGovIO2qqOHQiR+Aa1qvbwoBY+JxuE7uEHVe47Uo7CcOai4MX12bDLENsNsLqWOWv5xEAO9AB+Lde6oOOhJNXdFKbUIFYgZD6uyNToLDweDkEm+ka7ZaSU5tLsxDV+KUaju0aRYPOzEcrpTQ2drY1XWUDL0WyPTbJEbivfFeBaRZPApfwriBNJYxlEcALz1j2LO1QmY2/DppTiIr7hcGKO1A=
  app: hearafrica-api
